name: eeharvest
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - pip:
      - -e . # install git checkout of eeharvest in editable mode
      - alive-progress>=2.4.1
      - earthengine-api>=0.1.334
      - eemont>=0.3.5
      - geemap>=0.19.0
      - termcolor>=2.1.1
      # -------------------------
      # Development dependencies:
      # -------------------------
      - jupyterlab
      - myst-parser
      - nbdime
      - nbstripout
      - pyscaffold
      - pyscaffoldext-dsproject
      - pytest
      - pytest-sugar
      - pytest-cov
      - sphinx
